### ISSUE TITLE
issue in compiling

### ISSUE THREAD

**Issue by orcim** [swl-x/MystiQ#115]
orcim@orcim-UX32VD ~/0work/_myTry/_media/mystiQ/mystiq $ qmake mystiq.pro
orcim@orcim-UX32VD ~/0work/_myTry/_media/mystiQ/mystiq $ make
g++ -c -pipe -O2 -flto -fno-fat-lto-objects -Wall -W -D_REENTRANT -fPIC -DDATA_PATH= -DVERSION_ID_STRING= -DOPERATION_TIMEOUT=30000 -DDEFAULT_THREAD_COUNT=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QUICKWIDGETS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o mainwindow.o ui/mainwindow.cpp
In file included from ui/mainwindow.cpp:20:0:
./ui_mainwindow.h: In member function ‘void Ui_MainWindow::setupUi(QMainWindow*)’:
./ui_mainwindow.h:92:25: error: ‘class QAction’ has no member named ‘setShortcutVisibleInContextMenu’; did you mean ‘setShortcutContext’?
         actionAddFiles->setShortcutVisibleInContextMenu(false);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         setShortcutContext
Makefile:1009: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1

**Comment by llamaret** [comment]
Operating System?
Qt versión?

Remember, mystiq only compiles with Qt >5.10

**Comment by orcim** [comment]
Linux (Mint 19.3)Qt 5.12Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Maikel Llamaret Heredia <notifications@github.com> Data: 21/04/20  13:47  (GMT+01:00) A: swl-x/MystiQ <MystiQ@noreply.github.com> Cc: orcim <orciml@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [swl-x/MystiQ] issue in compiling (#115) 

Operating System?

Qt versión?



Remember, mystiq only compiles with Qt >5.10





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/swl-x/MystiQ/issues/115#issuecomment-617130314",

"url": "https://github.com/swl-x/MystiQ/issues/115#issuecomment-617130314",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by stevenpusser** [comment]
Can you provide  a list of the build-depends you installed to build it?

On Debian 10 thru Sid, for example, they are
               libnotify-dev,
               libqt5opengl5-dev (>= 5.10),
               qtdeclarative5-dev (>= 5.10),
               qtbase5-dev (>= 5.10),
               qtbase5-dev-tools (>= 5.10),
               qtmultimedia5-dev  (>= 5.10)

and are successful building packages in the cloud on the OBS: https://build.opensuse.org/package/show/home:stevepassert/mystiq

However, Mint 19.X is based on Ubuntu Bionic 18.04, and should have only Qt 5 5.9.5. How do you say you have 5.12?
